### ISSUE TITLE
An error when running schnetpack_qm9.py

### ISSUE THREAD

**Issue by wmmxk** [atomistic-machine-learning/schnetpack#138]

**Comment by wmmxk** [comment]
After I install this package, I run the following command, 
schnetpack_qm9.py train schnet /home/wxk/Data/schnet/data /home/wxk/Data/schnet/model --split 10000 1000.
I run into this error. It is related to the data loader. Is it because of the version of my PyTorch ? I am using 1.1.0 version.  

**FYI:** the error:
INFO:root:Parse xyz files...
INFO:root:Parsed:  10000 / 133885
INFO:root:Parsed:  20000 / 133885
INFO:root:Parsed:  30000 / 133885
INFO:root:Parsed:  40000 / 133885
INFO:root:Parsed:  50000 / 133885
INFO:root:Parsed:  60000 / 133885
INFO:root:Parsed:  70000 / 133885
INFO:root:Parsed:  80000 / 133885
INFO:root:Parsed:  90000 / 133885
INFO:root:Parsed: 100000 / 133885
INFO:root:Parsed: 110000 / 133885
INFO:root:Parsed: 120000 / 133885
INFO:root:Parsed: 130000 / 133885
INFO:root:Done.
INFO:root:Downloading list of evil molecules...
INFO:root:Done.
INFO:root:create splits...
INFO:root:load data...
INFO:root:calculate statistics...
INFO:root:statistics will be calculated...
Traceback (most recent call last):
  File "/home/wxk/.conda/envs/schnet/bin/schnetpack_qm9.py", line 340, in <module>
    mean, stddev = train_loader.get_statistics(train_args.property, True, atomref, split_file=split_path)
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/data.py", line 408, in get_statistics
    for row in self:
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/data.py", line 115, in __getitem__
    properties[Structure.cell] = torch.FloatTensor(at.cell.astype(np.float32))
AttributeError: 'Cell' object has no attribute 'astype'

**Comment by mgastegger** [comment]
This problem is due to a change of `cell` in the new version of ASE. It is now no longer a numpy array, but an object. We have already fixed this in the new master branch.

There were a few major changes in master. We merged all the different dataset specific scripts into one. The `schnetpack_qm9.py` script is now called as `spk_run.py train schnet qm9 ...`, the remaining options are the same as before.

**Comment by bartolsthoorn** [comment]
The eval command is also different, I have made changes to the README in this PR: https://github.com/atomistic-machine-learning/schnetpack/pull/140

**Comment by liuxiaotong15** [comment]
maybe you need update pip : )

**Comment by ktschuett** [comment]
Yes, pull latest schnetpack version and update ase. We will update our pip version asap.

**Comment by wmmxk** [comment]
Thanks for your replies. I cloned the repo and install it again and upgraded the ase package (3.18.0).
Now I run into this error. I run the script in this way: spk_run.py train schnet qm9 /home/wxk/data /home/wxk/model/ --split 10000 10000 --cuda


FYI, the error message:
 File "/home/wxk/.conda/envs/schnet/bin/spk_run.py", line 30, in main
    dataset = get_dataset(train_args)
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/utils/script_utils/data.py", line 117, in get_dataset
    remove_uncharacterized=args.remove_uncharacterized,
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/datasets/qm9.py", line 114, in __init__
    **kwargs
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/datasets/__init__.py", line 56, in __init__
    self.download()
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/datasets/__init__.py", line 72, in download
    self._download()
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/datasets/qm9.py", line 136, in _download
    self._load_data(evilmols)
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/datasets/qm9.py", line 230, in _load_data
    self.add_systems(all_atoms, all_properties)
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/schnetpack/data/atoms.py", line 280, in add_systems
    with connect(self.dbpath) as conn:
  File "/home/wxk/.conda/envs/schnet/lib/python3.6/site-packages/ase/db/core.py", line 159, in connect
    raise ValueError('No file extension or database type given')
ValueError: No file extension or database type given

**Comment by Stefaanhess** [comment]
Hey @wmmxk ,
your dbpath should link to the database file:

spk_run.py train schnet qm9 /home/wxk/data/qm9.db /home/wxk/model/ --split 10000 10000 --cuda

should work

**Comment by wmmxk** [comment]
I really appreciate your reply. It starts training. Could I know how long it will take to train on a computer with a single GeForce GTX 1070 card?

BTW, are there some blogs or videos about introducing schnet? (Maybe I should not ask a question like this here.)
