### ISSUE TITLE
Memory requirements for material project dataset

### ISSUE THREAD

**Issue by OMalenfantThuot** [atomistic-machine-learning/schnetpack#182]
Hi.
I hope you're doing great!

I'm using the training script interfaced with the Material Project dataset.

For a reason I don't understand, the CUDA memory requirements are really high. I'm using the same GPU than precedently, and I have to set batch_size to 4 instead of 256 or 512 in previous cases.

The problem can be reproduced with:
```
python spk_run.py from_json model/args.json
```
with the following `args.json` : 
```
{
    "apikey": null,
    "batch_size": 8,
    "checkpoint_interval": 1,
    "cuda": true,
    "cutoff": 10.0,
    "cutoff_function": "cosine",
    "datapath": "data/mp.db",
    "dataset": "matproj",
    "environment_provider": "torch",
    "features": 128,
    "interactions": 6,
    "keep_n_checkpoints": 3,
    "log_every_n_epochs": 1,
    "logger": "csv",
    "lr": 0.0001,
    "lr_decay": 0.8,
    "lr_min": 1e-06,
    "lr_patience": 25,
    "max_epochs": 5000,
    "max_steps": null,
    "mode": "train",
    "model": "schnet",
    "modelpath": "model/",
    "n_epochs": 1000,
    "num_gaussians": 50,
    "overwrite": false,
    "parallel": false,
    "property": "energy_per_atom",
    "seed": null,
    "split": [
        1000,
        100
    ],
    "split_path": null
}
```

I get the following error:
```
INFO:root:Random state initialized with seed 2849811532
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at data/mp.db
INFO:root:create splits...
INFO:root:load data...
INFO:schnetpack.data.loader:statistics will be calculated...
INFO:root:building model...
INFO:root:The model you built has: 455809 parameters
INFO:root:training...
Traceback (most recent call last):
  File "/home/olimt/projects/rrg-cotemich-ac/olimt/programs/schnetpack/src/scripts/spk_run.py", line 125, in <module>
    main(args)
  File "/home/olimt/projects/rrg-cotemich-ac/olimt/programs/schnetpack/src/scripts/spk_run.py", line 67, in main
    trainer.train(device, n_epochs=args.n_epochs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/train/trainer.py", line 263, in train
    raise e
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/train/trainer.py", line 190, in train
    result = self._model(train_batch)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/atomistic/model.py", line 61, in forward
    inputs["representation"] = self.representation(inputs)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/representation/schnet.py", line 234, in forward
    v = interaction(x, r_ij, neighbors, neighbor_mask, f_ij=f_ij)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/representation/schnet.py", line 75, in forward
    v = self.cfconv(x, r_ij, neighbors, neighbor_mask, f_ij)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/nn/cfconv.py", line 83, in forward
    y = self.agg(y, pairwise_mask)
  File "/home/olimt/miniconda3/envs/ml/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/lustre03/project/6004866/olimt/programs/schnetpack/src/schnetpack/nn/base.py", line 185, in forward
    input = input * mask[..., None]
RuntimeError: CUDA out of memory. Tried to allocate 326.00 MiB (GPU 0; 15.75 GiB total capacity; 12.29 GiB already allocated; 174.12 MiB free; 2.25 GiB cached)
```
Of course, you might be able to make it work on a GPU with more memory.
Is it expected when studying a periodic system or is it a problem?

Thanks a lot!

**Comment by mgastegger** [comment]
Hi, the problem seems to be the size of the systems in the materials project. Considering the periodic boundary conditions and that the materials can be quite dense, there will be a lot of atoms in the environment with a cutoff radius of 10 Angstrom. You could try reducing the cutoff to 5A, which is what we did for the benchmarks.

**Comment by OMalenfantThuot** [comment]
With a 5 Angstrom cutoff, I was able to use batch sizes of 32 structures, which is not so bad.

Maybe the default parameters (batch_size 100, cutoff 10 and environment_provider "simple") should be changed for this dataset.

Thank you for the answer. It's appreciated.
