### ISSUE TITLE
training error with BehlerSFBlock

### ISSUE THREAD

**Issue by neojie** [atomistic-machine-learning/schnetpack#210]
Hi, 
I tried using  `BehlerSFBlock` representation as follows but did not succeed.

```
import schnetpack as spk
from schnetpack.datasets import MD17
from torch.optim import Adam
import schnetpack.train as trn
import os
import numpy as np
import matplotlib.pyplot as plt
import torch

train_dir = './train'
if not os.path.exists(train_dir):
    os.makedirs(train_dir)
cutoff_radius = 8
from schnetpack.environment import AseEnvironmentProvider
data = MD17('../mydata.db',collect_triples=True,environment_provider= AseEnvironmentProvider(cutoff_radius))

atoms, properties = data.get_properties(0)

train, val, test = spk.train_test_split(
        data=data,
        num_train=4000,
        num_val=2000,
        split_file= "split.npz",
    )

train_loader = spk.AtomsLoader(train, batch_size=10, shuffle=True)
val_loader = spk.AtomsLoader(val, batch_size=10)


means, stddevs = train_loader.get_statistics(
    spk.datasets.MD17.energy, divide_by_atoms=True
)
n_features = 128
n_radial = 4
n_angular = 0
mode = 'Behler'

reps = spk.representation.BehlerSFBlock(n_radial =n_radial,
                     n_angular=n_angular,
                     elements=frozenset(np.array(data[0]['_atomic_numbers'])),
                     cutoff_radius=cutoff_radius,
                     mode = mode)
reps = spk.representation.StandardizeSF(reps, train_loader)

energy_model = spk.atomistic.Atomwise(
    n_in=n_features,
    property=MD17.energy,
    mean=means[MD17.energy],
    stddev=stddevs[MD17.energy],
    derivative=MD17.forces,
    negative_dr=True
)

model = spk.AtomisticModel(representation=reps, output_modules=energy_model)


# tradeoff
rho_tradeoff = 0.1

# loss function
def loss(batch, result):
    # compute the mean squared error on the energies
    diff_energy = batch[MD17.energy]-result[MD17.energy]
    err_sq_energy = torch.mean(diff_energy ** 2)

    # compute the mean squared error on the forces
    diff_forces = batch[MD17.forces]-result[MD17.forces]
    err_sq_forces = torch.mean(diff_forces ** 2)

    # build the combined loss function
    err_sq = rho_tradeoff*err_sq_energy + (1-rho_tradeoff)*err_sq_forces

    return err_sq


# build optimizer
optimizer = Adam(model.parameters(), lr=1e-4)

# set up metrics
metrics = [
    spk.metrics.MeanAbsoluteError(MD17.energy),
    spk.metrics.MeanAbsoluteError(MD17.forces)
]

# construct hooks
hooks = [
    trn.CSVHook(log_path=train_dir, metrics=metrics),
    trn.ReduceLROnPlateauHook(
        optimizer,
        patience=5, factor=0.8, min_lr=1e-6,
        stop_after_min=True
    )
]


trainer = trn.Trainer(
    model_path=train_dir,
    model=model,
    hooks=hooks,
    loss_fn=loss,
    optimizer=optimizer,
    train_loader=train_loader,
    validation_loader=val_loader,
)


# check if a GPU is available and use a CPU otherwise
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

# determine number of epochs and train
n_epochs = 2000
print('*****start to train******')
trainer.train(device=device, n_epochs=n_epochs)
print('*****end of train*****')

```
The error message is as follows,

```

Traceback   (most recent call last):
--
File   "spk_train_bp.py", line 139, in <module>
trainer.train(device=device, n_epochs=n_epochs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/train/trainer.py",   line 263, in train
raise e
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/train/trainer.py",   line 190, in train
result =   self._model(train_batch)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/atomistic/model.py",   line 64, in forward
outs.update(output_model(inputs))
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/atomistic/output_modules.py",   line 138, in forward
yi =   self.out_net(inputs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/container.py",   line 92, in forward
input =   module(input)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/nn/blocks.py",   line 67, in forward
return   self.out_net(inputs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/container.py",   line 92, in forward
input =   module(input)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py",   line 541, in __call__
result =   self.forward(*input, **kwargs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/nn/base.py",   line 59, in forward
y = super(Dense,   self).forward(inputs)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/linear.py",   line 87, in forward
return   F.linear(input, self.weight, self.bias)
File   "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/functional.py",   line 1372, in linear
output =   input.matmul(weight.t())
RuntimeError: size mismatch,   m1: [1600 x 12], m2: [128 x 64] at   /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:290


```

**Comment by mgastegger** [comment]
The problem are the `n_features` you pass to ` spk.atomistic.Atomwise`. Behler symmetry functions are special, as the number of features is predetermined based on the number of radial and angular functions given. This means unless you are lucky the given `n_features` will mismatch with the one built in the `SFBlock`. An easy way around this is to use the `n_symfuncs` attribute, which contains the number of features generated by the requested configuration (in this example 12) e.g:

```
energy_model = spk.atomistic.Atomwise(
    n_in=reps.n_symfuncs,
    property=MD17.energy,
    mean=means[MD17.energy],
    stddev=stddevs[MD17.energy],
    derivative=MD17.forces,
    negative_dr=True
)
```
I would also recommend to move
```
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"
```
to before the `get_statistics` call, so that the GPU can be used at this point already.
In addition, I would switch the `spk.atomistic.Atomwise` layer to `spk.atomistic.ElementalAtomwise`. Standard symmetry functions give the same features for different central atoms. `ElementalAtomwise` uses different energy networks for the different elements, as in the original Behler implementations.

**Comment by neojie** [comment]
Thank you. It solved the problem and runs smoothly if I use `spk.atomistic.Atomwise`. However, if I switch to  `spk.atomistic.ElementalAtomwise`,  I got the following error message. 
```
Traceback (most recent call last):
  File "spk_train_bp.py", line 138, in <module>
    trainer.train(device=device, n_epochs=n_epochs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 263, in train
    raise e
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 190, in train
    result = self._model(train_batch)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/atomistic/model.py", line 64, in forward
    outs.update(output_model(inputs))
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/atomistic/output_modules.py", line 138, in forward
    yi = self.out_net(inputs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/nn/blocks.py", line 215, in forward
    gated_network = self.gate(atomic_numbers) * self.network(representation)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/gpfs/loomis/project/kklee/jd848/conda_envs/jd37/lib/python3.7/site-packages/schnetpack/nn/blocks.py", line 110, in forward
    return torch.cat([net(inputs) for net in self.mlps], 2)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:278
```
It seems that this error is due to the size mismatch [https://discuss.pytorch.org/t/runtimeerror-cuda-runtime-error-710/61751/11](url) .

**Comment by mgastegger** [comment]
This is strange, for me it seemed to work. Did you delete the old model directory before restarting the training with the `spk.atomistic.ElementalAtomwise` block?

**Comment by neojie** [comment]
Yes, I have deleted the `train` folder. Anyway, `spk.atomistic.Atomwise` works and I will stick to it in this case. Thank you!
