### ISSUE TITLE
Issue with materials project test script

### ISSUE THREAD

**Issue by caesiumong** [atomistic-machine-learning/schnetpack#22]
Hi, 

I am getting an error when trying to train the network using the included script for training the materials project data. The model seems to train fine when I set `--property` to anything other than `band_gap`, but when I use `band_gap` I am getting some `KeyError`:

```
Traceback (most recent call last):
  File "matproj.py", line 273, in <module>
    mean, stddev = train_loader.get_statistics(train_args.property, False)
  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/schnetpack/data.py", line 408, in get_statistics
    for row in self:
  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/paperspace/anaconda3/envs/ml/lib/python3.6/site-packages/schnetpack/data.py", line 100, in __getitem__\n    prop = row.data[p]\nKeyError: \'band_gap\'\n'
```

Any help would be greatly appreciated. Thank you.

**Comment by caesiumong** [comment]
I fixed the issue by modifying these lines
```
                        query = m.query(criteria={'nelements': N, 'is_compatible': True, 'nsites': ns},
                                        properties=['structure', 'energy_per_atom', 'formation_energy_per_atom',
                                                    'total_magnetization',
                                                    'material_id', 'warnings'])
```
and
```
                                con.write(at, data={MaterialsProject.EPerAtom: q['energy_per_atom'],
                                                    MaterialsProject.EformationPerAtom: q['formation_energy_per_atom'],
                                                    MaterialsProject.TotalMagnetization: q['total_magnetization']})
```
in `src/schnetpack/datasets/matproj.py`.

**Comment by ktschuett** [comment]
Thanks for letting us know!
