### ISSUE TITLE
 Schnetpack MD code which is in pbc_update branch not competible with  Behler-Parrinello method ?

### ISSUE THREAD

**Issue by otayfuroglu** [atomistic-machine-learning/schnetpack#246]
Hello,
Upon my request last month, the Schnetpack MD code on the master branch was compatible with the Behler-Parrinello method (by adding require collect_triples).

However, according to the error shown below, it is understood that the Schnetpack MD code in the **pbc_update** branch is not compatible with the Behler-Parrinello method. 
Can you make the necessary corrections in order for the MD code in this branch to work?

Bests wishes,

Error;
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/truba/home/otayfuroglu/miniconda3/envs/deep/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/truba/home/otayfuroglu/miniconda3/envs/deep/lib/python3.7/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/truba_scratch/otayfuroglu/deepMOF/HDNNP/schnetpack/schnetpack_pbc/schnetpack/src/schnetpack/atomistic/model.py", line 65, in forward
    inputs["representation"] = self.representation(inputs)
  File "/truba/home/otayfuroglu/miniconda3/envs/deep/lib/python3.7/site-packages/torch/nn/modules/module.py", line 744, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/truba_scratch/otayfuroglu/deepMOF/HDNNP/schnetpack/schnetpack_pbc/schnetpack/src/schnetpack/representation/hdnn.py", line 240, in forward
    "Angular symmetry functions require "
schnetpack.representation.hdnn.HDNNException: Angular symmetry functions require `collect_triples=True` in AtomsData.

**Comment by mgastegger** [comment]
Hello,

I have added the fixes for using BP functions to the `update` branch, which combines all the functionality of `pbc_update` with a few additional improvements. Amybe you can try switching to this branch. If

**Comment by otayfuroglu** [comment]
thank you @mgastegger 

bests wishes,
