### ISSUE TITLE
RuntimeError: Schnetpack MD on multiple GPU

### ISSUE THREAD

**Issue by otayfuroglu** [atomistic-machine-learning/schnetpack#253]
Hello,
Before I open "Schnetpack MD on multiple GPU" #245 issue but I could not get any answer. I don't know how it happened but now it works on multiple gpu.  But now, when I was run Schnetpack MD simulation on two GPU, I get following runtime error;
**Note: I'm running the Schnetpack MD code through the update brach.**

Traceback (most recent call last):
  File "../schnetpack/run_md_withSchnetpack.py", line 221, in <module>
    main(molecule_path=args.mol_path, md_type=args.md_type,
  File "../schnetpack/run_md_withSchnetpack.py", line 206, in main
    simulator.simulate(n_steps)
  File "../schnetpack/schnetpack_update/schnetpack/src/schnetpack/md/simulator.py", line 78, in simulate
    self.calculator.calculate(self.system)
  File "../schnetpack/schnetpack_update/schnetpack/src/schnetpack/md/calculators/schnet_calculator.py", line 91, in calculate
    self._update_system(system)
  File "/../schnetpack/schnetpack_update/schnetpack/src/schnetpack/md/calculators/basic_calculators.py", line 121, in _update_system
    self.results[p].view(
RuntimeError: shape '[8, 1, 1]' is invalid for input of size 4

I would be very happy if you help,
Bests,

**Comment by ktschuett** [comment]
This should be possible in the next major version using pytorch lightning.
