### ISSUE TITLE
Errors when downloading materials dataset

### ISSUE THREAD

**Issue by jhrmnn** [atomistic-machine-learning/schnetpack#255]
With current master, I'm getting the following errors:
```
Traceback (most recent call last):
  File "/srv/hdd/jhermann/.cache/conda/envs/long-range/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/hdd/jhermann/.cache/conda/envs/long-range/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/srv/hdd/jhermann/Research/Projects/long-range/longrange/scripts/materials_dataset.py", line 44, in <module>
    ds = generate_materials_dataset(
  File "/srv/hdd/jhermann/Research/Projects/long-range/longrange/scripts/materials_dataset.py", line 19, in generate_materials_dataset
    print(repr(orig_ds[0]))
  File "/srv/hdd/jhermann/Research/Projects/long-range/extern/schnetpack/src/schnetpack/data/atoms.py", line 202, in __getitem__
    at, properties = self.get_properties(idx)
  File "/srv/hdd/jhermann/Research/Projects/long-range/extern/schnetpack/src/schnetpack/data/atoms.py", line 336, in get_properties
    properties[pname] = torch.FloatTensor(row.data[pname].copy())
AttributeError: 'float' object has no attribute 'copy'
```

This seems to fix the issue, don't know if it's a correct fix:

```diff
diff --git a/src/schnetpack/data/atoms.py b/src/schnetpack/data/atoms.py
index a9d8707..ceb9772 100644
--- a/src/schnetpack/data/atoms.py
+++ b/src/schnetpack/data/atoms.py
@@ -327,7 +327,12 @@ class AtomsData(Dataset):
         # extract properties
         properties = {}
         for pname in self.load_only:
-            properties[pname] = torch.FloatTensor(row.data[pname].copy())
+            value = row.data[pname]
+            try:
+                value = value.copy()
+            except AttributeError:
+                pass
+            properties[pname] = torch.tensor(value)

         # extract/calculate structure
         properties = _convert_atoms(
```

**Comment by ktschuett** [comment]
Fixed, copy is gone.
