### ISSUE TITLE
GPU is being used, even with --cuda disabled

### ISSUE THREAD

**Issue by hejops** [atomistic-machine-learning/schnetpack#324]
I tried evaluating the QM9 dataset with `--cuda`, but the following error is produced. Training with `--cuda` works fine though. Is it possible to use a GPU on a different device?

```
$ spk_run.py train schnet qm9 ./database.db ./model --split 100 100 --cuda

...

INFO:root:...training done!

$ spk_run.py eval database.db model --split test --cuda

INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at ./database.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:loading trained model...
INFO:root:evaluating...

/home/user/.local/lib/python3.8/site-packages/schnetpack/data/atoms.py:327: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  properties[pname] = torch.FloatTensor(prop)
/home/user/.local/lib/python3.8/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
  warnings.warn('Use get_global_number_of_atoms() instead',
/home/user/.local/lib/python3.8/site-packages/schnetpack/data/atoms.py:327: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:180.)
  properties[pname] = torch.FloatTensor(prop)
/home/user/.local/lib/python3.8/site-packages/ase/atoms.py:967: VisibleDeprecationWarning: Use get_global_number_of_atoms() instead
  warnings.warn('Use get_global_number_of_atoms() instead',

Traceback (most recent call last):
  File "/home/user/.local/bin/spk_run.py", line 124, in <module>
    main(args)
  File "/home/user/.local/bin/spk_run.py", line 90, in main
    evaluate(
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/utils/script_utils/evaluation.py", line 31, in evaluate
    results += evaluate_dataset(metrics, model, loaders[datasplit], device)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/utils/script_utils/evaluation.py", line 49, in evaluate_dataset
    result = model(batch)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/atomistic/model.py", line 41, in forward
    inputs["representation"] = self.representation(inputs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/representation/schnet.py", line 215, in forward
    x = self.embedding(atomic_numbers)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument index in method wrapper_index_select)
```

**Comment by Stefaanhess** [comment]
Hey @hejops 
the issue seems to be that some tensors are stored on the CPU and others on the GPU. This  causes the error. I tried to reproduce the issue with the master branch, but it worked out well for me. Are you using the current master branch or the pip version?

**Comment by hejops** [comment]
I'm using the pip version. I'll try the master branch and give you an update.

**Comment by hejops** [comment]
I tried to do training on master (5dd3d3f), but the following CUDA error is produced. Both my GPUs are indeed in use, but I thought that shouldn't matter since I didn't specify `--cuda`. Is this behaviour intended?

```
$ spk_run.py train schnet qm9 ./database.db ./model --split 5 5

INFO:root:Random state initialized with seed 1913397670
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at ./database.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:cached statistics was loaded...
INFO:root:building model...
INFO:root:The model you built has: 455809 parameters
INFO:root:training...
Traceback (most recent call last):
  File "/home/user/.local/bin/spk_run.py", line 123, in <module>
    main(args)
  File "/home/user/.local/bin/spk_run.py", line 62, in main
    trainer = get_trainer(args, model, train_loader, val_loader, metrics)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/utils/script_utils/training.py", line 50, in get_trainer
    trainer = spk.train.Trainer(
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/train/trainer.py", line 60, in __init__
    self.restore_checkpoint()
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/train/trainer.py", line 143, in restore_checkpoint
    self.state_dict = torch.load(chkpt)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/user/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 528, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by Stefaanhess** [comment]
Since your modelpath does already exist, the script tries to continue the training session that has been stored in `./model`. Therefore it also uses the args that are stored in `args.json`. Could you try it again with a new modelpath? e.g. delete `./model` or use `./model2`

**Comment by hejops** [comment]
Deleted both the model and the database just to be sure:

```
INFO:root:Random state initialized with seed 1424436646
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at ./database.db
INFO:root:create splits...
INFO:root:load data...
INFO:schnetpack.data.loader:statistics will be calculated...
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=46 : all CUDA-capable devices are busy or unavailable
Traceback (most recent call last):
  File "/home/user/.local/bin/spk_run.py", line 123, in <module>
    main(args)
  File "/home/user/.local/bin/spk_run.py", line 48, in main
    mean, stddev = get_statistics(
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/utils/script_utils/data.py", line 44, in get_statistics
    mean, stddev = train_loader.get_statistics(
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/data/loader.py", line 197, in get_statistics
    for row in self:
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 34, in _pin_memory_loop
    data = pin_memory(data)
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 54, in pin_memory
    return {k: pin_memory(sample) for k, sample in data.items()}
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 54, in <dictcomp>
    return {k: pin_memory(sample) for k, sample in data.items()}
  File "/home/user/.local/lib/python3.8/site-packages/torch/utils/data/_utils/pin_memory.py", line 50, in pin_memory
    return data.pin_memory()
RuntimeError: cuda runtime error (46) : all CUDA-capable devices are busy or unavailable at /pytorch/aten/src/THC/THCCachingHostAllocator.cpp:278
```

By the way, I think the instructions for installing from source might be incomplete. In order to get the executables to run from any location, I had to include the `/src/scripts` directory in my `PATH`, and `chmod` all the files (only one of them had execute permissions).

**Comment by Stefaanhess** [comment]
Ok, this seems to be an issue with the dataloader. It seems like `pin_memory` was `True`, which caused the dataloader to copy some data to the GPUs which are blocked. I created a new branch "issue_324" where I removed `pin_memory`. Could you try, if this solves the issue?
For the installation: did you use `pip install .`?

**Comment by hejops** [comment]
Yes, training has started successfully. Pretty slow on CPU, but I guess that's to be expected. I'll give it a try with `--cuda` when one of my GPUs is freed up. Thanks a lot for the quick fix.

Also, the installation worked properly now, guess I did something wrongly the first time.

**Comment by hejops** [comment]
One of my GPUs is free now, but I think torch might be trying to access the GPU that is still in use. Is it possible to specify the GPU I want to use? Or do I have to configure my GPU differently?

```
$ nvidia-smi 

Fri Sep  3 15:14:00 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA Quadro R...  On   | 00000000:3B:00.0  On |                  N/A |
| 67%   85C    P0   118W / 125W |   1145MiB /  7974MiB |     96%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA Quadro R...  On   | 00000000:5E:00.0 Off |                  N/A |
| 30%   40C    P8     6W / 125W |     13MiB /  7982MiB |      0%   E. Process |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1853      G   /usr/lib/xorg/Xorg                 41MiB |
|    0   N/A  N/A     36734      C   ...1-1/internal/bin/gdesmond      571MiB |
|    0   N/A  N/A     37603      G   gnome-control-center               38MiB |
|    0   N/A  N/A     39495      G   /usr/lib/xorg/Xorg                182MiB |
|    0   N/A  N/A    810034      G   /usr/lib/firefox/firefox           40MiB |
|    0   N/A  N/A   1059174      G   /usr/bin/gnome-shell              155MiB |
|    1   N/A  N/A      1853      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A     39495      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+

$ spk_run.py eval ./database.db ./model --split test --overwrite --cuda

INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at ./database.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:loading trained model...
Traceback (most recent call last):
  File "/home/user/.local/bin/spk_run.py", line 123, in <module>
    main(args)
  File "/home/user/.local/bin/spk_run.py", line 83, in main
    model = spk.utils.load_model(
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/utils/spk_utils.py", line 135, in load_model
    model = torch.load(model_path, map_location=map_location)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 857, in persistent_load
    load_tensor(data_type, size, key, _maybe_decode_ascii(location))
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 846, in load_tensor
    loaded_storages[key] = restore_location(storage, location)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 827, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/home/user/.local/lib/python3.8/site-packages/torch/serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "/home/user/.local/lib/python3.8/site-packages/torch/_utils.py", line 79, in _cuda
    return new_type(self.size()).copy_(self, non_blocking)
  File "/home/user/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 528, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

**Comment by hejops** [comment]
The good news, however, is that `spk_run.py` works perfectly when both of my GPUs are free. Though only the first GPU is being used, the performance is much better, as expected.

Any suggestions on how to configure GPU usage would be much appreciated.

**Comment by ktschuett** [comment]
You can specify the device by setting the environment variable CUDA_VISIBLE_DEVICES, e.g.
`CUDA_VISIBLE_DEVICES=0 python spk_run.yp ...`
