### ISSUE TITLE
Tutorial 2: 'numpy.ndarray' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by hejops** [atomistic-machine-learning/schnetpack#328]
I'm trying out tutorial 2 (as of commit 422c6e649cf7a0d6c1489419e11d3f63dd9f84d2), but I'm encountering the following error in the second last cell:

```
Keys: ['_atomic_numbers', '_positions', '_neighbors', '_cell', '_cell_offset', '_atom_mask', '_neighbor_mask']
Traceback (most recent call last):
  File "tutorial_02_qm9_nn.py", line 294, in <module>
    print("Truth:", props[QM9.U0].cpu().numpy()[0])
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'
```

Does anyone know what might be wrong?

**Comment by Stefaanhess** [comment]
Hey @hejops ,
it seems like the behaviour of the datasets has changed, but the tutorials have not been updated. The tutorial assumes to get `torch.Tensor` objects from `.get_properties()`, but the function returns `numpy.ndarray`.
could you try if this works out well: `print("Truth:", props[QM9.U0])` ?

**Comment by hejops** [comment]
Yes, that works, printing an array with a single element (a negative float). I guess the line for "Prediction" should also be modified, right?

**Comment by Stefaanhess** [comment]
The line for prediction should run fine, because the prediction is the outcome of the model, which should be a Tensor. Did you try it out? If this line generates an error, I would guess that it must be related to the shapes.
If you get an error for that line, try: `print('Prediction:', pred[QM9.U0].detach().cpu().numpy())` instead

**Comment by hejops** [comment]
Actually, I'm getting a different error at the line `pred = model(inputs)`:

```
Traceback (most recent call last):
  File "tutorial_02_qm9_nn.py", line 298, in <module>
    pred = model(inputs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/atomistic/model.py", line 65, in forward
    inputs["representation"] = self.representation(inputs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/schnetpack/representation/schnet.py", line 218, in forward
    x = self.embedding(atomic_numbers)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 158, in forward
    return F.embedding(
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/functional.py", line 2043, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking arugment for argument index in method wrapper_index_select)
```

This is not related to https://github.com/atomistic-machine-learning/schnetpack/issues/324, I hope? `device` was set to cuda.

**Comment by hejops** [comment]
After deleting the `qm9tut` directory and re-running both training and evaluation with `CUDA_VISIBLE_DEVICES=0,1`, the last two `print` statements run as intended. Thanks for your help.
