### ISSUE TITLE
float division by zero

### ISSUE THREAD

**Issue by gravity-lhg** [atomistic-machine-learning/schnetpack#329]
Traceback (most recent call last):
  File "D:/Python_workplace/environment/Scripts/spk_run.py", line 123, in <module>
    main(args)
  File "D:/Python_workplace/environment/Scripts/spk_run.py", line 65, in main
    trainer.train(device, n_epochs=args.n_epochs)
  File "D:\Python_workplace\environment\lib\site-packages\schnetpack\train\trainer.py", line 267, in train
    raise e
  File "D:\Python_workplace\environment\lib\site-packages\schnetpack\train\trainer.py", line 241, in train
    val_loss /= n_val
ZeroDivisionError: float division by zero

useing “spk_run.py train schnet qm9 ../data/qm9.db ../model/ --split 10000 10000 --cuda” to run. I don't know what wrong with this

**Comment by Stefaanhess** [comment]
Hey @gravity-lhg ,
I have no idea what is going on here. I just tried to run your command (without `--cuda, because our cluster is down atm), and everything works out well. I do not think that cuda is the issue here. Could you check how many datapoints are in the dataset file? Maybe something went wrong with the download. You could also try to delete the model folder and the dataset and even reinstall schnetpack to see if something went wrong with the installation?

**Comment by gravity-lhg** [comment]
thank you @Stefaanhess 
I have identified the problem. I did not clean up the previous ckeckpoints. And thank you again!!!

**Comment by Stefaanhess** [comment]
ok, great!
