### ISSUE TITLE
OSError when restart SchnetPack MD

### ISSUE THREAD

**Issue by otayfuroglu** [atomistic-machine-learning/schnetpack#333]
Hi folks,

When my SchnetPack MD simulation killed by HPC cluster accidentally  I want to restart my simulation but, I encounter error fallow:

Traceback (most recent call last):
  File "/truba_scratch/yzorlu/deepMOF/HDNNP/schnetpack/run_md_withSchnetpack.py", line 341, in <module>
    simulator.simulate(n_steps)
  File "/truba_scratch/yzorlu/deepMOF/HDNNP/schnetpack/schnetpack_master/schnetpack/src/schnetpack/md/simulator.py", line 82, in simulate
    hook.on_simulation_start(self)
  File "/truba_scratch/yzorlu/deepMOF/HDNNP/schnetpack/schnetpack_master/schnetpack/src/schnetpack/md/simulation_hooks/logging_hooks.py", line 517, in on_simulation_start
    self.file = h5py.File(self.filename, "a", libver="latest")
  File "/truba/home/yzorlu/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 455, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/truba/home/yzorlu/miniconda3/lib/python3.8/site-packages/h5py/_hl/files.py", line 211, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (file is already open for write/SWMR write (may use <h5clear file> to clear file consistency flags))

**As said above, I am trying  to clear file consistency flags using the h5clear tool, but the .hdf5 file is completely corrupted**. Can you please help me? 

Best regards..

**Comment by ktschuett** [comment]
Hi,
I am not an expert in the HDF5 file format. But if an HDF5 file is completely corrupted, I don't think there is much you can do except restarting the simulation.

Best,
Kristof
