### ISSUE TITLE
Training on property "gap" crashes with experiment=qm9

### ISSUE THREAD

**Issue by NiklasGebauer** [atomistic-machine-learning/schnetpack#431]
The training crashes when calling `spktrain experiment=qm9 globals.property=gap`. In my opinion, it should be possible to train on all properties contained in QM9 using that config.
The problem is that there are no atomrefs in the qm9.db metadata for the gap while the config for the experiment `qm9` specifies `remove_atomrefs: True` https://github.com/atomistic-machine-learning/schnetpack/blob/0f5043981b9b7a01ebb52daf3e6bb8a9cbed7a08/src/schnetpack/configs/experiment/qm9.yaml#L19 and `add_atomrefs: True` https://github.com/atomistic-machine-learning/schnetpack/blob/0f5043981b9b7a01ebb52daf3e6bb8a9cbed7a08/src/schnetpack/configs/experiment/qm9.yaml#L36

I think we should either add atomrefs of 0 for gap (and other properties that do not have atomrefs like homo, lumo, etc.) to the db or ignore the setting of `remove_atomrefs` and `add_atomrefs` if the atomrefs for the target property cannot be found in metadata. Which solution do you prefer? Or do you have any other idea how to fix this?

**Comment by NiklasGebauer** [comment]
For reference, here is the traceback:

```
Traceback (most recent call last):
  File "schnetpack/src/schnetpack/cli.py", line 157, in train
    trainer.fit(model=task, datamodule=datamodule)
  File "python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1174, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1492, in _call_setup_hook
    self.datamodule.setup(stage=fn)
  File "schnetpack/src/schnetpack/data/datamodule.py", line 190, in setup
    self._setup_transforms()
  File "schnetpack/src/schnetpack/data/datamodule.py", line 315, in _setup_transforms
    t.datamodule(self)
  File "schnetpack/src/schnetpack/transform/atomistic.py", line 92, in datamodule
    self.atomref = atrefs[self._property].detach()
KeyError: 'gap'
```

**Comment by ktschuett** [comment]
We should not make this kind of stuff implicit. This is bad design and will only lead to confusion. I think it would be better to refactor the configs to make it clearer how to treat a particular property. For example, the gap should also use average pooling instead of summing and the dipole moment should be predicted with the corresponding output layer.
