### ISSUE TITLE
Error during model fitting: <input> file not found?

### ISSUE THREAD

**Issue by EnoshI** [atomistic-machine-learning/schnetpack#472]
So I am working with a custom dataset created with:
```
import os
import torch
import pymatgen
import numpy as np
import schnetpack as spk
import schnetpack.transform as trn
from scipy import interpolate
import matplotlib.pyplot as plt
from ase import Atoms
import numpy as np
from schnetpack.datasets import ASEAtomsData
from pymatgen.ext.matproj import MPRester
#from mp-api import MPRester
from pymatgen.core import Structure

with MPRester('Bp0Q8XcNOhuFD2HK') as mpr:
    data = mpr.query(criteria={'has_bandstructure':True,'nelements': 2}, properties = ['task_id',"structure",'efermi'])
    dos = {data[0]['task_id']: mpr.get_dos_by_material_id(data[0]['task_id'])}
    new_eleDOS = {data[0]['task_id']:1}
    elemental_dos = {data[0]['task_id']:1}
    #eleDOS_unshifted = {data[0]['task_id']:1}
    for i in range(3): # len(data)
        dos[data[i]['task_id']] = mpr.get_dos_by_material_id(data[i]['task_id'])
        elemental_dos[data[i]['task_id']] = dos[data[i]['task_id']].get_element_dos()
        #eleDOS_unshifted[data[i]['task_id']] = dos[data[i]['task_id']].get_element_dos()
        for elem in elemental_dos[data[i]['task_id']]:
            elemental_dos[data[i]['task_id']][elem].energies = elemental_dos[data[i]['task_id']][elem].energies - data[i]['efermi']

        xnew = np.arange(-10.2, 0.2, 0.1)
        for elem in elemental_dos[data[i]['task_id']]:
            total = []
            spin1 = []
            spin2 = []
            for spin in elemental_dos[data[i]['task_id']][elem].densities:
                if spin.value == 1:
                    for density in elemental_dos[data[i]['task_id']][elem].densities[spin]:
                        spin1.append(density)
                else:
                    for density in elemental_dos[data[i]['task_id']][elem].densities[spin]:
                        spin2.append(density)
            if len(spin2) == 0:
                total = np.array(spin1)
            else:
                total = np.array(spin1) + np.array(spin2)
            elemental_dos[data[i]['task_id']][elem].densities['total'] = total
            y = elemental_dos[data[i]['task_id']][elem].densities['total']
            tck = interpolate.splrep(elemental_dos[data[i]['task_id']][elem].energies, y, s=0)
            elemental_dos[data[i]['task_id']][elem].densities['SplInterpE'] = xnew
            elemental_dos[data[i]['task_id']][elem].densities['SplInterpDOS'] = interpolate.splev(xnew, tck, der=0)

        tally = 0
        for j in elemental_dos[data[i]['task_id']]:
            if tally == 0:
                temp = {j.symbol: elemental_dos[data[i]['task_id']][j]}
                tally = 1
            else:
                temp[j.symbol] = elemental_dos[data[i]['task_id']][j]
        new_eleDOS[data[i]['task_id']] = temp

    #for spin in elemental_dos[data[i]['task_id']][elem].densities:
    #    spins.append(spin)
    #x = elemental_dos[data[i]['task_id']][elem].energies
    #y = elemental_dos[data[i]['task_id']][elem].densities[spins[0]]
    #tck = interpolate.splrep(x, y, s=0)
    #xnew = np.arange(-11,1,0.1)
    #ynew = interpolate.splev(xnew, tck, der=0)

    #plt.figure()
    #plt.plot(x, y, 'x', xnew, ynew, x, y, 'b')
    #plt.legend(['Linear', 'Cubic Spline', 'True'])
    #plt.axis([-0.05, 6.33, -1.05, 1.05])
    #plt.title('Cubic-spline interpolation of DOS')
    #plt.show()

    atms = {data[0]['task_id']:1}
    for i in range(3): # len(data)
        s = data[i]['structure']
        atms[data[i]['task_id']] = Atoms(numbers=s.atomic_numbers, positions=s.cart_coords, cell=s.lattice.matrix, pbc=True,)

    del temp
    del i
    del j
    del tally
atoms_list,properties_list = [],[]
for at in atms:
    atoms_list.append(atms[at])

for m in elemental_dos:
    properties = {}
    properties['atom_numbers'] = []
    properties['DOS'] = []
    #properties['pDOS'] = []
    track = 1
    for elem in elemental_dos[m]:
        if track == 1:
            properties['energy_levels'] = np.array(elemental_dos[m][elem].densities['SplInterpE'])
            properties['DOS'].append(elemental_dos[m][elem].densities['SplInterpDOS'])
            #for n in new_eleDOS[m][elem].densities:
                #properties['pDOS'].append(np.array(new_eleDOS[m][elem].densities[n]))
            track = 0
        else:
            properties['DOS'].append(elemental_dos[m][elem].densities['SplInterpDOS'])
            #for n in new_eleDOS[m][elem].densities:
                #properties['pDOS'].append(np.array(new_eleDOS[m][elem].densities[n]))
        properties['atom_numbers'].append(elem.number)
    properties['atom_numbers'] = np.array(properties['atom_numbers'])
    properties['DOS'] = np.matrix(properties['DOS'])
    #properties['pDOS'] = np.array(properties['pDOS'])
    properties_list.append(properties)
dataset = ASEAtomsData.create('./testn1.db',distance_unit='Ang',transforms = [
        trn.ASENeighborList(cutoff=5.),trn.CastTo32(),trn.AddOffsets(dataset, add_mean=True, add_atomrefs=True)
                                        ], property_unit_dict={'energy_levels':'eV',
                                                             'DOS':'states/eV/atom',
                                                             'atom_numbers':'number'})
dataset.add_systems(properties_list,atoms_list)
```

I am also using a custom loss function module that is required for the way I'm handling my data outputs:
```
from torch.nn.modules.loss import _Loss
from torch import Tensor
class dos_loss(_Loss):
    def __init__(self, size_average=None, reduce=None) -> None:
        super(dos_loss, self).__init__(size_average, reduce)

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        return loss_fn(input, target)

    def loss_fn(output, true):
        def mse(actual, pred):
            return torch.square(torch.subtract(actual, pred)).mean()

        loss = 0
        try:
            for i in range(len(true)):
                for elem in range(len(true[i]['atom_numbers'])):
                    pred_dos = output[i]['scalar_representation'][
                        true[i]['_atomic_numbers'] == true[i]['atom_numbers'][elem]].sum(axis=0)
                    loss += mse(true[i]['DOS'][elem], pred_dos)
        except:
            for elem in range(len(true['atom_numbers'])):
                pred_dos = output['scalar_representation'][true['_atomic_numbers'] == true['atom_numbers'][elem]].sum(
                    axis=0)
                loss += mse(true['DOS'][elem], pred_dos)
        # except:
        # loss= 10
        return loss
```

and finally, I am getting an error during the model training where it is searching for some <input> file during the last line:
```
import os
import torch
import torchmetrics
import schnetpack as spk
import schnetpack.transform as trn
import pytorch_lightning as pl
import matplotlib.pyplot as plt
import numpy as np
from schnetpack.data.datamodule import AtomsDataModule
from Test import dos_loss as customLoss

results = dataset

pDOSdata = './pDOSdata'
#qm9tut = './qm9tut'
if not os.path.exists(pDOSdata):
    os.makedirs(pDOSdata)

pDOS_data = AtomsDataModule(
    './testn1.db',
    batch_size= 1,
    num_train=1,
    num_val=1,
    transforms=[
        trn.ASENeighborList(cutoff=5.),
        trn.CastTo32()
    ],
    split_file=os.path.join(pDOSdata, "split.npz")
)
pDOS_data.prepare_data()
pDOS_data.setup()

#test_data = dict([(a,b.float()) if b.dtype==torch.float64 else (a,b) for a,b in dataset[0].items()])

cutoff = 5.0
n_atom_basis = 104

pairwise_distance = spk.atomistic.PairwiseDistances() # calculates pairwise distances between atoms
radial_basis = spk.nn.GaussianRBF(n_rbf=20, cutoff=cutoff)
schnet = spk.representation.SchNet(
    n_atom_basis=n_atom_basis, n_interactions=3,
    radial_basis=radial_basis,
    cutoff_fn=spk.nn.CosineCutoff(cutoff)
)

pred_DOS = spk.atomistic.Atomwise(n_in=n_atom_basis, output_key=results)

nnpot = spk.model.NeuralNetworkPotential(
    representation=schnet,
    input_modules=[pairwise_distance],
    output_modules=[pred_DOS],
    postprocessors=[trn.CastTo64()]
)

output_DOS = spk.task.ModelOutput(
    name=results,
    loss_fn=customLoss(),
    loss_weight=1.,
    metrics={
        "MAE": torchmetrics.MeanAbsoluteError()
    }
)

task = spk.task.AtomisticTask(
    model=nnpot,
    outputs=[output_DOS],
    optimizer_cls=torch.optim.AdamW,
    optimizer_args={"lr": 1e-4}
)

logger = pl.loggers.TensorBoardLogger(save_dir=pDOSdata)
callbacks = [
    spk.train.ModelCheckpoint(
        model_path=os.path.join(pdostut, "best_inference_model"),
        save_top_k=1,
        monitor="val_loss"
    )
]

trainer = pl.Trainer(
    callbacks=callbacks,
    logger=None,
    default_root_dir=pDOSdata,
    max_epochs=3, # for testing, we restrict the number of epochs
)
trainer.fit(task, datamodule=pDOS_data)
```

I'm getting an error that says: 
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'

**Comment by mgastegger** [comment]
Do you know, at which point this error occurs, e.g. does the loading of the dataset work?

One thing that definitively looks strange is that you use an initialized dataset as the key for naming the model outputs instead of a string (`results = dataset`).
I also can't find where you define the `pdostut` directory used for checkpointing. This should be set to an existing directory, e.g. the `pDOSdata` used as the `default_root_dir` in the task.

**Comment by EnoshI** [comment]
sorry, I was messing around with different parts of the code to pinpoint the error. Here is the proper one; as long as I delete the split files my dataset loads properly, and I am still getting the same error:  

`RuntimeError: DataLoader worker (pid(s) 56593, 56594, 56595, 56596, 56597, 56598, 56599, 56600) exited unexpectedly
`
which seems to be because of 
`FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
`
where this is happening in the line
`trainer.fit(task, datamodule=pDOS_data)`

from:

```
import os
import torch
import torchmetrics
import schnetpack as spk
import schnetpack.transform as trn
import pytorch_lightning as pl
import matplotlib.pyplot as plt
import numpy as np
from schnetpack.data.datamodule import AtomsDataModule
from Test import dos_loss as customLoss

results = dataset

pDOSdata = './pDOSdata'
#qm9tut = './qm9tut'
if not os.path.exists(pDOSdata):
    os.makedirs(pDOSdata)

pDOS_data = AtomsDataModule(
    './testn1.db',
    batch_size= 1,
    num_train=1,
    num_val=1,
    transforms=[
        trn.ASENeighborList(cutoff=5.),
        trn.CastTo32()
    ],
    split_file=os.path.join(pDOSdata, "split.npz")
)
pDOS_data.prepare_data()
pDOS_data.setup()

#test_data = dict([(a,b.float()) if b.dtype==torch.float64 else (a,b) for a,b in dataset[0].items()])

cutoff = 5.0
n_atom_basis = 104

pairwise_distance = spk.atomistic.PairwiseDistances() # calculates pairwise distances between atoms
radial_basis = spk.nn.GaussianRBF(n_rbf=20, cutoff=cutoff)
schnet = spk.representation.SchNet(
    n_atom_basis=n_atom_basis, n_interactions=3,
    radial_basis=radial_basis,
    cutoff_fn=spk.nn.CosineCutoff(cutoff)
)

pred_DOS = spk.atomistic.Atomwise(n_in=n_atom_basis, output_key='pDOS')

nnpot = spk.model.NeuralNetworkPotential(
    representation=schnet,
    input_modules=[pairwise_distance],
    output_modules=[pred_DOS],
    postprocessors=[trn.CastTo64()]
)

output_DOS = spk.task.ModelOutput(
    name='pDOS',
    loss_fn=customLoss(),
    loss_weight=1.,
    metrics={
        "MAE": torchmetrics.MeanAbsoluteError()
    }
)

task = spk.task.AtomisticTask(
    model=nnpot,
    outputs=[output_DOS],
    optimizer_cls=torch.optim.AdamW,
    optimizer_args={"lr": 1e-4}
)

logger = pl.loggers.TensorBoardLogger(save_dir=pDOSdata)
callbacks = [
    spk.train.ModelCheckpoint(
        model_path=os.path.join(pDOSdata, "best_inference_model"),
        save_top_k=1,
        monitor="val_loss"
    )
]

trainer = pl.Trainer(
    callbacks=callbacks,
    logger=None,
    default_root_dir=pDOSdata,
    max_epochs=3, # for testing, we restrict the number of epochs
)
trainer.fit(task, datamodule=pDOS_data)

```

**Comment by Stefaanhess** [comment]
Hey @EnoshI ,

could you maybe copy + paste the full exception trace? I can not really understand what the script is trying to load at this point (model, dataset, ...?). What is your current working directory, from which you start the script? Is it `/Users/enosh/PycharmProjects/DOS_model`? Could you maybe also delete the `pDOSdata` if it exists at the beginning of you script? Just to make sure it is empty and the model the script is not trying to load a broken run.

**Comment by EnoshI** [comment]
Hello @Stefaanhess, thanks for checking in!

So I made sure to rm split* in my working directory, which is indeed `/Users/enosh/PycharmProjects/DOS_model`

I also remove rm -r pDOSdata/ each time. I am still getting the same issues. The script has properly loaded the dataset, but during the model fitting call `trainer.fit(task, datamodule = pDOS_data)` it may be having issues with the loading? I am not sure. 

I know my loss function has some problems with its internal definition, but even if I make the loss module's function simply return loss = 0, I am getting the exact same errors. 

The exception trace is extremely long:
```
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
  | Name    | Type                   | Params
---------------------------------------------------
0 | model   | NeuralNetworkPotential | 153 K 
1 | outputs | ModuleList             | 0     
---------------------------------------------------
153 K     Trainable params
0         Non-trainable params
153 K     Total params
0.613     Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py:563: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
    exitcode = _main(fd, parent_sentinel)  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
        prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
prepare(preparation_data)    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
      File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    code, fname = _get_code_from_file(run_name, path_name)    
with io.open_code(decoded_path) as f:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 252, in _get_code_from_file
    with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/enosh/PycharmProjects/DOS_model/<input>'
Traceback (most recent call last):
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 86, in <module>
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in fit
    self._call_and_handle_interrupt(
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 723, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1345, in _run_train
    self._run_sanity_check()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1413, in _run_sanity_check
    val_loop.run()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 112, in advance
    batch = next(data_fetcher)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 259, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/pytorch_lightning/utilities/fetching.py", line 273, in _fetch_next_batch
    batch = next(iterator)
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "/Users/enosh/PycharmProjects/DOS_model/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 60434, 60435, 60436, 60437, 60438, 60439, 60440, 60441) exited unexpectedly
```

**Comment by Stefaanhess** [comment]
I have never seen an error like this in schnetpack, but it seems to be related to the data. Could you maybe try the following steps:

1. Read datapoints from the DB:
````
from ase.db import connect

with connect(db_path) as db:
    for idx in range(len(db)):
        row = db.get(idx+1)
print(row.data)
````
2. Load batches from the dataset and move them to GPU
````
dataloader = pDOS_data.train_dataloader()
for batch in dataloader:
    batch = {property_name: data.cuda() for property_name, data in batch.items()}
````
3. Replace the dataset in your script with one of the prepared datasets (e.g. QM9). Then test if the same error shows up again.

**Comment by Stefaanhess** [comment]
4. Delete the database file and create a new one. Maybe something went wrong during the creation of the data

**Comment by EnoshI** [comment]
Hello, so I solved the issue! I needed to set the aggregation mode to None, change my output key to 'DOS', and modify the Nnpot  module to fit my custom dataset. Thanks for your time!

**Comment by Stefaanhess** [comment]
Nice to hear :)
