### ISSUE TITLE
BanGap Property and MultiGPU Error

### ISSUE THREAD

**Issue by MiracAydin1** [atomistic-machine-learning/schnetpack#480]
Dear All,

I am trying to train new version of Schnetpack with OMDB dataset. I copied the tutorial of QM9 and changed necessary parts for OMDB. I am running codes on NVIDIA RTX A4500 GPUs. But when I try to run the code with 1 GPU, it gives the following error:

```
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1361, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/datamodule.py", line 190, in setup
    self._setup_transforms()
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/datamodule.py", line 315, in _setup_transforms
    t.datamodule(self)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/transform/atomistic.py", line 123, in datamodule
    self.atomref = atrefs[self._property].detach()
KeyError: 'band_gap'
```

As I understand, there is problem about the name of propery "bandgap".

Secondly, when I try to use 2 GPUs with the parameter of "devices2" on the training step, it gives the following error. I have read the documentation of SchNet but I could not find how to distribute the model onto 2 GPUs. 

```
File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Here is my code to train the package for OMDB:

```
import os
import schnetpack as spk
from schnetpack.datasets import OrganicMaterialsDatabase as OMDB
import schnetpack.transform as trn

import torch
import torchmetrics
import pytorch_lightning as pl

omdb_folder = './omdb_folder'
if not os.path.exists('omdb_folder'):
    os.makedirs(omdb_folder)

omdbdata = OMDB(
    datapath='./omdb_gap.db',
    batch_size=32,
    num_train=10000,
    num_val=1000,
    transforms=[
        trn.ASENeighborList(cutoff=5.),
        trn.RemoveOffsets(OMDB.BandGap, remove_mean=True, remove_atomrefs=True),
        trn.CastTo32()
    ],
    property_units={OMDB.BandGap: 'eV'},
    num_workers=1,
    split_file=os.path.join(omdb_folder, "split.npz"),
    pin_memory=True, # set to false, when not using a GPU
    load_properties=[OMDB.BandGap], #only load BandGap property
    raw_path='./OMDB-GAP1_v1.1.tar.gz'
)

omdbdata.prepare_data()

cutoff = 5.
n_atom_basis = 30

pairwise_distance = spk.atomistic.PairwiseDistances() # calculates pairwise distances between atoms
radial_basis = spk.nn.GaussianRBF(n_rbf=20, cutoff=cutoff)
schnet = spk.representation.SchNet(
    n_atom_basis=n_atom_basis, n_interactions=3,
    radial_basis=radial_basis,
    cutoff_fn=spk.nn.CosineCutoff(cutoff)
)
pred_gap = spk.atomistic.Atomwise(n_in=n_atom_basis, output_key=OMDB.BandGap)

nnpot = spk.model.NeuralNetworkPotential(
    representation=schnet,
    input_modules=[pairwise_distance],
    output_modules=[pred_gap],
    postprocessors=[trn.CastTo64(), trn.AddOffsets(OMDB.BandGap, add_mean=True, add_atomrefs=True)]
)

output_gap = spk.task.ModelOutput(
    name=OMDB.BandGap,
    loss_fn=torch.nn.MSELoss(),
    loss_weight=1.,
    metrics={
        "MAE": torchmetrics.MeanAbsoluteError()
    }
)

task = spk.task.AtomisticTask(
    model=nnpot,
    outputs=[output_gap],
    optimizer_cls=torch.optim.AdamW,
    optimizer_args={"lr": 1e-4}
)

logger = pl.loggers.TensorBoardLogger(save_dir=omdb_folder)
callbacks = [
    spk.train.ModelCheckpoint(
        model_path=os.path.join(omdb_folder, "best_inference_model"),
        save_top_k=1,
        monitor="val_loss"
    )
]

trainer = pl.Trainer(
    callbacks=callbacks,
    logger=logger,
    default_root_dir=omdb_folder,
    max_epochs=10, # for testing, we restrict the number of epochs
    accelerator='gpu',
    devices=2
)
trainer.fit(task, datamodule=omdbdata)
```

Do you have any suggestion to solve these problems?

Best regards,
Miraç

**Comment by Stefaanhess** [comment]
Hey @MiracAydin1,

your first problem seems to come from the atomrefs. It seems like you want to remove the atomrefs in 

>    transforms=[
>        trn.ASENeighborList(cutoff=5.),
>        trn.RemoveOffsets(OMDB.BandGap, remove_mean=True, remove_atomrefs=True),
>        trn.CastTo32()
>    ],

 but the dataset does not provide atomrefs. So you would either need to provide atomref data to the database, or set `remove_atomrefs=False`. This also needs to be done in postprocessing.
The other issue with multiple GPUs seems to be related to [this pytorch issue](https://discuss.pytorch.org/t/runtimeerror-an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-finished-its-bootstrapping-phase/145462/4).

**Comment by MiracAydin1** [comment]
Hi @Stefaanhess,

Thank you so much for your message.

I set `remove_atomrefs=False` for all occurrences and `devices=1` but now it gives the following error:

```
Traceback (most recent call last):
  File "omdb_train.py", line 87, in <module>
    trainer.fit(task, datamodule=omdbdata)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 603, in fit
    call._call_and_handle_interrupt(
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 645, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1037, in _run
    self._call_setup_hook()  # allow user to setup lightning_module in accelerator environment
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in _call_setup_hook
    self._call_lightning_datamodule_hook("setup", stage=fn)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1361, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/datamodule.py", line 190, in setup
    self._setup_transforms()
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/datamodule.py", line 315, in _setup_transforms
    t.datamodule(self)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/transform/atomistic.py", line 126, in datamodule
    stats = _datamodule.get_stats(
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/datamodule.py", line 331, in get_stats
    stats = calculate_stats(
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/stats.py", line 44, in calculate_stats
    for props in tqdm(dataloader):
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/atoms.py", line 266, in __getitem__
    props = self._get_properties(
  File "/opt/miniconda3/envs/schnetpack20/lib/python3.8/site-packages/schnetpack/data/atoms.py", line 343, in _get_properties
    torch.tensor(row.data[pname].copy()) * self.conversions[pname]
AttributeError: 'float' object has no attribute 'copy'
```

**Comment by Stefaanhess** [comment]
The data in your database seems to be stored in the wrong format. all properties need to be stored as `np.array` instead of float. did you create the database by yourself, or with the download function in schnetpack?
You can fix this with:

`
    from ase.db import connect

    db_path = "path to your db"
    db_path_new = "omdb_fixed.db"
    with connect(db_path) as db:
        with connect(db_path_new) as new_db:
            db_new.metadata = db.metadata
            for idx in range(len(db)):
                atmsrw = db.get(idx+1)
                data = {property_name: np.array([property]) for property_name, property in atmsrw.data.items()}
                db_new.write(atmsrw.toatoms(), data=data)
`
If you used the OMDB.download method for creating it, we might need to fix this in schnetpack.

**Comment by MiracAydin1** [comment]
Hi @Stefaanhess,

I did not create the database by myself, I just downloaded the archive file which is OMDB-GAP1_v1.1.tar.gz.

Then  I used the following code snippet to create database. I did not do anything manually:

```
omdbdata = OMDB(
    datapath='./omdb_gap.db',
    batch_size=32,
    num_train=10000,
    num_val=1000,
    transforms=[
        trn.ASENeighborList(cutoff=5.),
        trn.RemoveOffsets(OMDB.BandGap, remove_mean=True, remove_atomrefs=True),
        trn.CastTo32()
    ],
    property_units={OMDB.BandGap: 'eV'},
    num_workers=1,
    split_file=os.path.join(omdb_folder, "split.npz"),
    pin_memory=True, # set to false, when not using a GPU
    load_properties=[OMDB.BandGap], #only load BandGap property
    raw_path='./OMDB-GAP1_v1.1.tar.gz'
)

omdbdata.prepare_data()
```
Let me try your solution to see what will happen. I will write here after testing your function.

**Comment by MiracAydin1** [comment]
Hi @Stefaanhess,

After implementing your solution and removing `raw_path` parameter, the model is training now properly. 

Thank you so much.

**Comment by Stefaanhess** [comment]
Good to hear. The bug should be fixed now
