### ISSUE TITLE
error in schnetpack/data/atoms.py

### ISSUE THREAD

**Issue by Asif-Iqbal-Bhatti** [atomistic-machine-learning/schnetpack#495]
Hallo,

I want to  train my data on materials project db but whenever I want to access the dataset it gives me this error:
    for g in example:
  File "/home/****/miniconda3/lib/python3.10/site-packages/schnetpack/data/atoms.py", line 266, in __getitem__
    props = self._get_properties(
  File "/home/******/miniconda3/lib/python3.10/site-packages/schnetpack/data/atoms.py", line 343, in _get_properties
    torch.tensor(row.data[pname].copy()) * self.conversions[pname]
AttributeError: 'float' object has no attribute 'copy'

Can you suggest how to avoid this error even in the source code you have inquired how it can be avoided. You are trying to copy the properties from the ASE db into the torch and then acces it. I am using schnet 2.0 for 1.0 there is no problem.

Groetjes,
Asif

**Comment by Stefaanhess** [comment]
Hi @Asif-Iqbal-Bhatti ,

sorry for the late reply!
We have changed the dtypes of scalar properties from `float` to `np.ndarray` in the new spk, but forgot to update this for materials project. I added a fix in #498.

Groetjes,
Stefaan

**Comment by Asif-Iqbal-Bhatti** [comment]
Still the problem is there, it says:
Traceback (most recent call last):
  File "/mnt/c/Users/abhatti/Desktop/SchNetPackModel_2.0/./sch_model_on_MP.py", line 180, in <module>
    data_loading()
  File "/mnt/c/Users/abhatti/Desktop/SchNetPackModel_2.0/./sch_model_on_MP.py", line 70, in data_loading
    for  v in example:
  File "/home/asifem/miniconda3/lib/python3.10/site-packages/schnetpack/data/atoms.py", line 266, in __getitem__
    props = self._get_properties(
  File "/home/asifem/miniconda3/lib/python3.10/site-packages/schnetpack/data/atoms.py", line 343, in _get_properties
    torch.tensor(row.data[pname].copy()) * self.conversions[pname]
AttributeError: 'float' object has no attribute 'copy'

The problem is coming from this part:
    def _get_properties(
        self, conn, idx: int, load_properties: List[str], load_structure: bool
    ):
        row = conn.get(idx + 1)

        # extract properties
        # TODO: can the copies be avoided?
        properties = {}
        properties[structure.idx] = torch.tensor([idx])
        for pname in load_properties:
            properties[pname] = (
                torch.tensor(row.data[pname].copy()) * self.conversions[pname]
            )

**Comment by Asif-Iqbal-Bhatti** [comment]
Hello STefaan,

Thank you for fixing but still I am facing the same issue:
Loading and splitting data ...
Available properties:
 |  formation_energy_per_atom
 |  energy_per_atom
 |  band_gap
 |  total_magnetization
Number of reference calculations: 126298
Number of train data: 10000
Number of validation data: 9000
Number of test data: 107298
126298
Traceback (most recent call last):
  File "/mnt/c/Users/abhatti/Desktop/SchNetPackModel_2.0/./sch_model_on_MP.py", line 180, in <module>
    data_loading()
  File "/mnt/c/Users/abhatti/Desktop/SchNetPackModel_2.0/./sch_model_on_MP.py", line 70, in data_loading
    for  k, v in example.items():
AttributeError: 'ASEAtomsData' object has no attribute 'items'

**Comment by Stefaanhess** [comment]
Did you re-download the database? You would need to do this in order to make the changes work.
Alternatively you could also loop over all columns in the database manually and update the types from `float` to `np.ndarray`. You could do something like this:
```
from ase.db import connect
import numpy as np

with connect("path-to-your-db") as db:
    for i in range(len(db)):
        data = db.get(i+1).data
        data = {k: np.array([v]) for k, v in data.items()}
        db.update(i+1, data=data)
```

But to me it seems like the error message has changed. The first error was related to the `_get_properties()` function and now the error seems to occur in your script. I am not sure what you are doing in the script.

**Comment by Asif-Iqbal-Bhatti** [comment]
Okay i did redownload the data:
I am following the qm9 tutorial but for Materials Project I just follow the example as on the webpage. My script is:
    print("Loading and splitting data ...")
    #key="xxxxxxxxxx"
    key="xxxxxxxxxxxxx"
    matprojdata = MaterialsProject(
        'hh.db',
        apikey = key,
        batch_size=100,
        num_train=10000,
        num_val=9000,
        transforms=[trn.ASENeighborList(cutoff=5.),],
        property_units={prop: 'eV'},
        num_workers=2,
        split_file=os.path.join(outData, "mat.npz"),
        pin_memory=False, # set to false, when not using a GPU
        load_properties=[prop], 
    )
    matprojdata.prepare_data()
    matprojdata.setup()
    
    
    print('Available properties:')
    for p in matprojdata.dataset.available_properties:  print(' | ', p);
    print('Number of reference calculations:', len(matprojdata.dataset))
    print('Number of train data:', len(matprojdata.train_dataset))
    print('Number of validation data:', len(matprojdata.val_dataset))
    print('Number of test data:', len(matprojdata.test_dataset))


    #means, stddevs = matprojdata.get_stats(
    #    prop, divide_by_atoms=True, remove_atomref=True
    #)
    #print('Mean atomization energy / atom:', means.item())
    #print('Std. dev. atomization energy / atom:', stddevs.item())
    
    example = matprojdata.dataset
    print(len(example))

    #
    for  k, v in example.items():
        print(k, v)

The error is coming here AttributeError: 'ASEAtomsData' object has no attribute 'items' but isaw for qm9 there is no error. Do I have to change the above line of code for MP or the tutorial for qm9 cannot be adapted to other database.

**Comment by Stefaanhess** [comment]
I am not sure where `example.items` comes from. The `schnetpack.data.AtomsData` class does not support a `.items()` function, as far as I know. So this is where the error happens. You could try `examples.iter_properties()`, which returns a dictionary of the data in the database. So `examples.iter_properties().items()` should work also.
I am still a bit confused, because `example.items()` also should yield an error for QM9.

**Comment by Asif-Iqbal-Bhatti** [comment]
Hello Stafaan,

I checked again and it is working now: I follow the tutorial on https://schnetpack.readthedocs.io/en/latest/tutorials/tutorial_01_preparing_data.html and use this

example = qm9data.dataset[0] ### for material project it would be matprojdata.dataset[0]
print('Properties:')

for k, v in example.items():
    print('-', k, ':', v.shape)

The problem was accessing the data. we have to specify [0] to have the items() in the dict otherwise it will throw "AttributeError: 'ASEAtomsData' object has no attribute 'items'". The framework is fine and it works for other database also. Again thank you.

**Comment by Stefaanhess** [comment]
nice to hear :)
