### ISSUE TITLE
Issue training Schnet on MaterialsProject

### ISSUE THREAD

**Issue by aarora4** [atomistic-machine-learning/schnetpack#526]
Hi, I am following the tutorial in the documentation for training Schnet on QM9 and trying to use MaterialsProject instead, but I am running into an error in the training. 

```python
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/schnetpack/data/atoms.py", line 266, in __getitem__
    props = self._get_properties(
  File "/usr/local/lib/python3.9/dist-packages/schnetpack/data/atoms.py", line 335, in _get_properties
    row = conn.get(idx + 1)
  File "/usr/local/lib/python3.9/dist-packages/ase/db/core.py", line 432, in get
    raise KeyError('no match')
KeyError: 'no match'
``` 

I'm having a hard time understanding what key it is looking for that it isn't finding.

My full implementation and the stacktrace for the error can be found [here](https://colab.research.google.com/drive/1VC8JAGwFX2f68Q-MrgkzvknwiEMK_Qi6?usp=sharing)

Any help would be much appreciated :)

**Comment by aarora4** [comment]
Update: I changed the the datapath for MaterialsProject by appending ./mptut/ (referencing this part of the QM9 tutorial)
`qm9tut = './qm9tut'
if not os.path.exists('qm9tut'):
    os.makedirs(qm9tut)`

Now, I am still running into a keyerror but it is a different one (KeyError: '_Rij'):

```python
[<ipython-input-38-ac6008477f4e>](https://localhost:8080/#) in <cell line: 66>()
     64     max_epochs=3, # for testing, we restrict the number of epochs
     65 )
---> 66 trainer.fit(task, datamodule=mp)
     67 
     68 # loss = trn.build_mse_loss([MaterialsProject.EformationPerAtom])

21 frames
[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    606             raise TypeError(f"`Trainer.fit()` requires a `LightningModule`, got: {model.__class__.__qualname__}")
    607         self.strategy._lightning_module = model
--> 608         call._call_and_handle_interrupt(
    609             self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    610         )

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/call.py](https://localhost:8080/#) in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     36             return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     37         else:
---> 38             return trainer_fn(*args, **kwargs)
     39 
     40     except _TunerExitException:

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _fit_impl(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    648             model_connected=self.lightning_module is not None,
    649         )
--> 650         self._run(model, ckpt_path=self.ckpt_path)
    651 
    652         assert self.state.stopped

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _run(self, model, ckpt_path)
   1101         self._checkpoint_connector.resume_end()
   1102 
-> 1103         results = self._run_stage()
   1104 
   1105         log.detail(f"{self.__class__.__name__}: trainer tearing down")

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _run_stage(self)
   1180         if self.predicting:
   1181             return self._run_predict()
-> 1182         self._run_train()
   1183 
   1184     def _pre_training_routine(self) -> None:

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _run_train(self)
   1193 
   1194         with isolate_rng():
-> 1195             self._run_sanity_check()
   1196 
   1197         # enable train mode

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _run_sanity_check(self)
   1265             # run eval step
   1266             with torch.no_grad():
-> 1267                 val_loop.run()
   1268 
   1269             self._call_callback_hooks("on_sanity_check_end")

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py](https://localhost:8080/#) in run(self, *args, **kwargs)
    197             try:
    198                 self.on_advance_start(*args, **kwargs)
--> 199                 self.advance(*args, **kwargs)
    200                 self.on_advance_end()
    201                 self._restarting = False

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py](https://localhost:8080/#) in advance(self, *args, **kwargs)
    150         if self.num_dataloaders > 1:
    151             kwargs["dataloader_idx"] = dataloader_idx
--> 152         dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
    153 
    154         # store batch level output per dataloader

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/loop.py](https://localhost:8080/#) in run(self, *args, **kwargs)
    197             try:
    198                 self.on_advance_start(*args, **kwargs)
--> 199                 self.advance(*args, **kwargs)
    200                 self.on_advance_end()
    201                 self._restarting = False

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py](https://localhost:8080/#) in advance(self, data_fetcher, dl_max_batches, kwargs)
    135 
    136         # lightning module methods
--> 137         output = self._evaluation_step(**kwargs)
    138         output = self._evaluation_step_end(output)
    139 

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py](https://localhost:8080/#) in _evaluation_step(self, **kwargs)
    232         """
    233         hook_name = "test_step" if self.trainer.testing else "validation_step"
--> 234         output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
    235 
    236         return output

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/trainer/trainer.py](https://localhost:8080/#) in _call_strategy_hook(self, hook_name, *args, **kwargs)
   1483 
   1484         with self.profiler.profile(f"[Strategy]{self.strategy.__class__.__name__}.{hook_name}"):
-> 1485             output = fn(*args, **kwargs)
   1486 
   1487         # restore current_fx when nested context

[/usr/local/lib/python3.9/dist-packages/pytorch_lightning/strategies/strategy.py](https://localhost:8080/#) in validation_step(self, *args, **kwargs)
    388         with self.precision_plugin.val_step_context():
    389             assert isinstance(self.model, ValidationStep)
--> 390             return self.model.validation_step(*args, **kwargs)
    391 
    392     def test_step(self, *args: Any, **kwargs: Any) -> Optional[STEP_OUTPUT]:

[/usr/local/lib/python3.9/dist-packages/schnetpack/task.py](https://localhost:8080/#) in validation_step(self, batch, batch_idx)
    198             pass
    199 
--> 200         pred = self.predict_without_postprocessing(batch)
    201         pred, targets = self.apply_constraints(pred, targets)
    202 

[/usr/local/lib/python3.9/dist-packages/schnetpack/task.py](https://localhost:8080/#) in predict_without_postprocessing(self, batch)
    233         pp = self.model.do_postprocessing
    234         self.model.do_postprocessing = False
--> 235         pred = self(batch)
    236         self.model.do_postprocessing = pp
    237         return pred

[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.9/dist-packages/schnetpack/task.py](https://localhost:8080/#) in forward(self, inputs)
    137 
    138     def forward(self, inputs: Dict[str, torch.Tensor]):
--> 139         results = self.model(inputs)
    140         return results
    141 

[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.9/dist-packages/schnetpack/model/base.py](https://localhost:8080/#) in forward(self, inputs)
    177             inputs = m(inputs)
    178 
--> 179         inputs = self.representation(inputs)
    180 
    181         for m in self.output_modules:

[/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py](https://localhost:8080/#) in _call_impl(self, *args, **kwargs)
   1499                 or _global_backward_pre_hooks or _global_backward_hooks
   1500                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501             return forward_call(*args, **kwargs)
   1502         # Do not call functions when jit is used
   1503         full_backward_hooks, non_full_backward_hooks = [], []

[/usr/local/lib/python3.9/dist-packages/schnetpack/representation/schnet.py](https://localhost:8080/#) in forward(self, inputs)
    138     def forward(self, inputs: Dict[str, torch.Tensor]):
    139         atomic_numbers = inputs[structure.Z]
--> 140         r_ij = inputs[structure.Rij]
    141         idx_i = inputs[structure.idx_i]
    142         idx_j = inputs[structure.idx_j]

KeyError: '_Rij'
```

**Comment by aarora4** [comment]
I was missing the pairwise distance module as an input.

**Comment by aarora4** [comment]
added pairwise_distance = spk.atomistic.PairwiseDistances() 
added input_modules=[pairwise_distance] when instantiating model
