### ISSUE TITLE
md.py load_model error

### ISSUE THREAD

**Issue by MartinEls** [atomistic-machine-learning/schnetpack#56]
By trying to load an existing model for md-calculations, I run into this error:

>>> model = md.load_model("test_model")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/schnetpack/md.py", line 377, in load_model
    model.load_state_dict(torch.load(os.path.join(modelpath, 'best_model')))
  File "/usr/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for AtomisticModel:
        Unexpected key(s) in state_dict: "output_modules.atomref.weight".

**Comment by ktschuett** [comment]
Which version are you using: pip or the git master branch? In the Github version this should not happen, since we're now storing the whole model and not just the weights.
