### ISSUE TITLE
Division by Zero

### ISSUE THREAD

**Issue by Dekken** [atomistic-machine-learning/schnetpack#60]
Hey folks,

I'm trying this out with the ROCM version of Pytorch so chances are there's an issue there 

```
python3 src/scripts/schnetpack_qm9.py train schnet ./tests/data/test_qm9.db .  --split 2 2 --cuda
INFO:root:Random state initialized with seed 1534720078
INFO:root:QM9 will be loaded...
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at ./tests/data/test_qm9.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:calculate statistics...
INFO:root:cached statistics was loaded...
INFO:root:The model you built has: 1676033 parameters
INFO:root:training...
Traceback (most recent call last):
  File "src/scripts/schnetpack_qm9.py", line 443, in <module>
    train(args, model, train_loader, val_loader, device)
  File "src/scripts/schnetpack_qm9.py", line 221, in train
    trainer.train(device)
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/train/trainer.py", line 239, in train
  File "/home/philix/.pyenv/versions/3.7.2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/train/trainer.py", line 217, in train
ZeroDivisionError: float division by zero
```

**Comment by Dekken** [comment]
Testing on nvidia now

**Comment by ktschuett** [comment]
Can you try with a training set thats larger than batch size, e.g. --split
200 200

**Comment by Dekken** [comment]
seems to be a ROCM problem
