### ISSUE TITLE
Problem with schnetpack_qm9.py

### ISSUE THREAD

**Issue by somnambWl** [atomistic-machine-learning/schnetpack#78]
Hello,

I would like to ask if _schnetpack_qm9.py_ is still working. No matter what I try, I eventually run into `RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441`. 

I only create a new virtualenv, pip install schnetpack and then I run:
`schnetpack_qm9.py train schnet QM9 TestRun --split 10000 10000 --cuda`       

Output is following (when I already downloaded QM9):
```
INFO:root:Random state initialized with seed 3679303364
INFO:root:QM9 will be loaded...
INFO:root:create splits...
INFO:root:load data...
INFO:root:calculate statistics...
INFO:root:cached statistics was loaded...
INFO:root:The model you built has: 1676133 parameters
INFO:root:training...
Traceback (most recent call last):
  File "/home/kubaw/.virtualenvs/schnet/bin/schnetpack_qm9.py", line 357, in <module>
    train(args, model, train_loader, val_loader, device)
  File "/home/kubaw/.virtualenvs/schnet/bin/schnetpack_qm9.py", line 177, in train
    trainer.train(device)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 216, in train
    raise e
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/train/trainer.py", line 144, in train
    result = self._model(train_batch)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/atomistic.py", line 55, in forward
    inputs['representation'] = self.representation(inputs)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/representation/schnet.py", line 191, in forward
    r_ij = self.distances(positions, neighbors, cell, cell_offset)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/nn/neighbors.py", line 76, in forward
    return atom_distances(positions, neighbors, cell, cell_offsets, return_directions=self.return_directions)
  File "/home/kubaw/.virtualenvs/schnet/lib/python3.7/site-packages/schnetpack/nn/neighbors.py", line 36, in atom_distances
    offsets = cell_offsets.bmm(cell)
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441
```

I am not sure where this error comes from because for me a basic pytorch nn is working.
I have also noticed that the version installed with pip needs a folder as datadir, the version installed with setup.py needs a .db file as datadir. It also seems that there is recent work on scripts using sacred, so it may also be, that old scripts are not working anymore. It would be great if you could confirm, that the script is working as then I could search for the origin of the error elsewhere; or if you had an idea where this error comes from.

**Comment by ktschuett** [comment]
Hi,
as you already noted, you should use:
`schnetpack_qm9.py train schnet QM9.db TestRun --split 10000 10000 --cuda`
with the current version instead of providing a directory. THis is because, we now store the atomref data from qm9 as metadata in the db file.

Otherwise, the script should work. This looks more like a problem with your GPU or python environment. Does it work without CUDA? Maybe, you have a jupyter notebook open in the background that is blocking the GPU?

P.S. There was an unrelated bug I just fix, so better pull before trying again.

**Comment by somnambWl** [comment]
Hello,

I have tried it again with the new version installed with _setup.py_. I got a similar error, but I managed to fix it in the end.
Here is the error:

```
INFO:root:Random state initialized with seed 2156320712
INFO:root:QM9 will be loaded...
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at QM9.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:calculate statistics...
INFO:schnetpack.data.loader:statistics will be calculated...
INFO:root:The model you built has: 1676033 parameters
INFO:root:training...
Traceback (most recent call last):
  File "/home/kubaw/.virtualenvs/schnet2/bin/schnetpack_qm9.py", line 4, in <module>
    __import__('pkg_resources').run_script('schnetpack==0.2.1', 'schnetpack_qm9.py')
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/EGG-INFO/scripts/schnetpack_qm9.py", line 591, in <module>
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/EGG-INFO/scripts/schnetpack_qm9.py", line 323, in train
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/train/trainer.py", line 248, in train
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/train/trainer.py", line 178, in train
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/atomistic.py", line 57, in forward
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/representation/schnet.py", line 211, in forward
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/nn/neighbors.py", line 122, in forward
  File "/home/kubaw/.virtualenvs/schnet2/lib/python3.7/site-packages/schnetpack-0.2.1-py3.7.egg/schnetpack/nn/neighbors.py", line 54, in atom_distances
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:441
```

However, I managed to fix it by reinstalling torch. 

```
pip uninstall torch
pip3 install https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
```

Before, it worked without CUDA and there was not jupyter notebook opened in the background.

Thanks for the help :)
