### ISSUE TITLE
Using trained model as ASE calculator

### ISSUE THREAD

**Issue by Dankomaister** [atomistic-machine-learning/schnetpack#8]
I'm trying to used a trained model as an calculator object in ASE, however i get an error.
```
Traceback (most recent call last):
  File "opti.py", line 30, in <module>
    dyn.run(fmax=0.01)
  File "/usr/local/lib/python3.6/dist-packages/ase/optimize/optimize.py", line 174, in run
    f = self.atoms.get_forces()
  File "/usr/local/lib/python3.6/dist-packages/ase/atoms.py", line 735, in get_forces
    forces = self._calc.get_forces(self)
  File "/usr/local/lib/python3.6/dist-packages/ase/calculators/calculator.py", line 460, in get_forces
    return self.get_property('forces', atoms)
  File "/usr/local/lib/python3.6/dist-packages/ase/calculators/calculator.py", line 493, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/usr/local/lib/python3.6/dist-packages/schnetpack/md.py", line 94, in calculate
    model_results = self.model(model_inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/schnetpack/atomistic.py", line 55, in forward
    inputs['representation'] = self.representation(inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/schnetpack/representation/schnet.py", line 199, in forward
    v = interaction(x, r_ij, neighbors, neighbor_mask, f_ij=f_ij)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/schnetpack/representation/schnet.py", line 52, in forward
    v = self.cfconv.forward(x, r_ij, neighbors, neighbor_mask, f_ij=f_ij)
  File "/usr/local/lib/python3.6/dist-packages/schnetpack/nn/cfconv.py", line 67, in forward
    y = torch.gather(y, 1, nbh)
RuntimeError: Invalid index in gather at /pytorch/aten/src/TH/generic/THTensorMath.cpp:620
```
Have been trying with different ASE scripts, geometry optimization, phonon dispersion calculation etc, but getting similar errors. Attached are the files for a geometry optimization of a 6,0 SWCNT with the trained model.

Any tips on how to fix this?

[6,0_opti.zip](https://github.com/atomistic-machine-learning/schnetpack/files/2421389/6.0_opti.zip)

**Comment by mgastegger** [comment]
There was a problem with the neighbor masks in the ASE interface when PBCs were used.

We fixed it and the optimization should now run properly.
