### ISSUE TITLE
max() arg is an empty sequence error

### ISSUE THREAD

**Issue by ivicts** [atomistic-machine-learning/schnetpack#94]
```
(schnetpack) victor@DEEPLEARN3:~/chemistry/Codes/schnetpack_reproduce$ python3 src/scripts/schnetpack_qm9.py train schnet data/seed_2000/energy_U0_cosine/data/qm9.db data/seed_2000/energy_U0_cosine/model --split 109000 1000 --cuda --property energy_U0 --cutoff_function cosine --seed 2000 --logger tensorboard
INFO:root:Random state initialized with seed 2000      
INFO:root:QM9 will be loaded...
INFO:schnetpack.data.atoms:The dataset has already been downloaded and stored at data/seed_2000/energy_U0_cosine/data/qm9.db
INFO:root:create splits...
INFO:root:load data...
INFO:root:calculate statistics...
INFO:root:cached statistics was loaded...
INFO:root:The model you built has: 1676033 parameters
INFO:root:training...
Traceback (most recent call last):
  File "src/scripts/schnetpack_qm9.py", line 606, in <module>
    train(args, model, train_loader, val_loader, device)
  File "src/scripts/schnetpack_qm9.py", line 328, in train
    args.modelpath, model, loss, optimizer, train_loader, val_loader, hooks=hooks
  File "/home/victor/anaconda3/envs/schnetpack/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/train/trainer.py", line 60, in __init__
  File "/home/victor/anaconda3/envs/schnetpack/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/train/trainer.py", line 119, in restore_checkpoint
ValueError: max() arg is an empty sequence
```

Hi, if I run the src/scripts/schnetpack_qm9.py it gives me error of  "max() arg is an empty sequence error", I have tried uninstall schnetpack and install again from the source.

**Comment by FarnazH** [comment]
Remove your modelpath, which I believe is `data/seed_2000/energy_U0_cosine/model` in your case, and then run the script again.

**Comment by ivicts** [comment]
```
(schnetpack) victor@DEEPLEARN3:~/chemistry/Codes/schnetpack_reproduce$ python3 src/scripts/schnetpack_qm9.py train schnet data/seed_2000/energy_U0_cosine/data/qm9.db --split 109000 1000 --cuda --property energy_U0 --cutoff_function cosine --seed 2000 --logger tensorboard
usage: schnetpack_qm9.py train schnet [-h] [--cuda] [--parallel]
                                      [--batch_size BATCH_SIZE]
                                      [--property {rotational_constant_A,rotational_constant_B,rotational_constant_C,dipole_moment,isotropic_polarizability,homo,lumo,gap,electronic_spatial_extent,zpve,energy_U0,energy_U,enthalpy_H,free_energy,heat_capacity}]
                                      [--remove_uncharacterized REMOVE_UNCHARACTERIZED]
                                      [--seed SEED] [--overwrite]
                                      [--split_path SPLIT_PATH]
                                      [--split SPLIT SPLIT]
                                      [--max_epochs MAX_EPOCHS] [--lr LR]
                                      [--lr_patience LR_PATIENCE]
                                      [--lr_decay LR_DECAY] [--lr_min LR_MIN]
                                      [--logger {csv,tensorboard}]
                                      [--log_every_n_epochs LOG_EVERY_N_EPOCHS]
                                      [--aggregation_mode {sum,avg}]
                                      [--features FEATURES]
                                      [--interactions INTERACTIONS]
                                      [--cutoff CUTOFF]
                                      [--cutoff_function {hard,cosine,mollifier}]
                                      [--num_gaussians NUM_GAUSSIANS]
                                      datapath modelpath
schnetpack_qm9.py train schnet: error: the following arguments are required: modelpath

```

the parser says I need the modelpath?

**Comment by FarnazH** [comment]
If the directory `model` exists, it tries to load a checkpointed model and you get the error. Just delete `model` directory and give it the modelpath you have been using. It should work then, I believe.
