### ISSUE TITLE
CUDA memory issue during optimization

### ISSUE THREAD

**Issue by xiaowei-xie** [atomistic-machine-learning/schnetpack#99]
I have been training on various size water clusters and trying to optimize a water 256 using the trained model. The training process worked fine, but when I try to optimize, I always get the following CUDA memory error. When I run on CPU, the optimization is pretty slow(5min per step). I would like to ask, is the requirement of this much memory a legitimate thing and what is causing it so memory intensive? Or do you have any idea what might went wrong?
Thank you in advance for any help your could possibly provide!

Traceback (most recent call last):
  File "optimize_water_256_wacsf.py", line 15, in <module>
    print("forces:", atoms.get_forces())
  File "/home/xiaowei/.local/lib/python3.6/site-packages/ase/atoms.py", line 714, in get_forces
    forces = self._calc.get_forces(self)
  File "/home/xiaowei/.local/lib/python3.6/site-packages/ase/calculators/calculator.py", line 519, in get_forces
    return self.get_property('forces', atoms)
  File "/home/xiaowei/.local/lib/python3.6/site-packages/ase/calculators/calculator.py", line 552, in get_property
    self.calculate(atoms, [name], system_changes)
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/ase_interface.py", line 92, in calculate
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/atomistic.py", line 61, in forward
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/representation/hdnn.py", line 366, in forward
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 494, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/representation/hdnn.py", line 238, in forward
  File "/home/xiaowei/miniconda3/lib/python3.6/site-packages/schnetpack-0.2.1-py3.6.egg/schnetpack/nn/neighbors.py", line 204, in neighbor_elements
RuntimeError: CUDA out of memory. Tried to allocate 1.68 GiB (GPU 0; 7.77 GiB total capacity; 6.02 GiB already allocated; 648.62 MiB free; 17.94 MiB cached)

The following is the code I have been using to run optimization.

import torch
from schnetpack.ase_interface import SpkCalculator
from ase import Atoms
from ase.io import read
from ase.optimize import BFGS

path_to_model = "XX_water_wacsf/best_model"
model = torch.load(path_to_model)

atoms = read('water_256.xyz')
calc = SpkCalculator(model, device="cuda")
atoms.set_calculator(calc)
print("forces:", atoms.get_forces())
print("total_energy", atoms.get_potential_energy())
dyn = BFGS(atoms,trajectory='water_256_opt_BFGS_wacsf.traj',restart='water_256_opt_BFGS_wacsf.pckl')
dyn.run(fmax=0.05)

**Comment by ktschuett** [comment]
@Stefaanhess Memory Leak? Could a decouple be missing in the calculator?

**Comment by ktschuett** [comment]
@xiaowei-xie Might be a memory leak... How long does it run until the error?  Do you have something like a jupyter notebook running in the background that uses the GPU?

**Comment by xiaowei-xie** [comment]
@ktschuett Thank you for the reply! I'm pretty sure that's the only thing using the GPU. It gets the error instantly after I run the code. I can run on CPU, but it also uses tons of memory(up to 40% of a work station's memory(128G)).

**Comment by ktschuett** [comment]
Ah,ok. I think the problem is that you use the default environment provider which assumes full connectivity. You should try:
```
from schnetpack.environment import AseEnvironmnetProvider

cutoff = 5. # or whatever you are using during training
calc = SpkCalculator(model, device="cuda", environment_provider=AseEnvironmnetProvider(cutoff))
```

**Comment by xiaowei-xie** [comment]
@ktschuett I changed the environment provider and got rid of the memory error. Thanks! But the optimization using GPU is pretty slow(30 min per step) and the GPU usage is almost 0%. Do you have any idea what the problem might be?

**Comment by ktschuett** [comment]
No, sorry. Perhaps you can try to use straight-forward gradient descent instead of BFGS? That should at least narrow it down where the time is spent...
